name: nonebot_flutter_webui_agent
description: 通过 API 管理你的 NoneBot
version: 0.1.8
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  http: ^1.2.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  toml: ^0.16.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
